name: Verificar existencia de README.md

on:
  push:
    branches: [main]

jobs:
  comprobar-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Verificar si README.md existe
        run: |
          if [ -f "README.md" ]; then
            echo "✅ El archivo README.md existe."
          else
            echo "⚠️ No se encontró README.md."
          fi
